# Generated by Django 5.2.11 on 2026-03-05 14:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='advertising_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='advertising_contact_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='advertising_title',
            field=models.CharField(blank=True, default='Par reklāmu', max_length=255),
        ),
        migrations.CreateModel(
            name='AdvertisingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price_month', models.CharField(blank=True, max_length=100)),
                ('price_week', models.CharField(blank=True, max_length=100)),
                ('price_day', models.CharField(blank=True, max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_banners', to='contacts.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
