# Generated by Django 5.2.11 on 2026-03-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactpage_advertising_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReportEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
