# Generated by Django 5.2.11 on 2026-03-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
