# Generated by Django 5.2.11 on 2026-02-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspage_category_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='news.author'),
        ),
    ]
