# Generated by Django 5.2.11 on 2026-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_globalsitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsitesettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='about',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='organization_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
