# Generated by Django 5.2.11 on 2026-02-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_globalsitesettings_logo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
