# Generated by Django 5.2.11 on 2026-02-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.advert'),
        ),
    ]
