# Generated by Django 5.2.11 on 2026-02-16 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_sections_alter_aboutpage_team'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='team',
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(max_length=50)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='about_pages', to='about.teammember'),
        ),
    ]
